import * as fs from "fs";
import * as path from "path";

/**
 * Apply Design System Theme
 * 
 * Takes AI-modified design JSON and applies it to the page.
 * Can either:
 * 1. Set data-theme attribute to use an existing theme
 * 2. Inject custom CSS variables as a new "custom" theme
 */

interface ThemeVariables {
    [key: string]: string;
}

interface ApplyDesignInput {
    selectedTheme?: string;  // Use existing theme by ID
    customVariables?: ThemeVariables;  // Or provide custom variables
}

const CSS_FILE = path.join(process.cwd(), "src", "design-system.css");
const INPUT_FILE = path.join(process.cwd(), "design-updated.json");
const INJECT_MARKER = "/* === AI CUSTOM THEME === */";

function readInputFile(): ApplyDesignInput {
    if (!fs.existsSync(INPUT_FILE)) {
        throw new Error(`Input file not found: ${INPUT_FILE}`);
    }
    return JSON.parse(fs.readFileSync(INPUT_FILE, "utf-8"));
}

function generateCustomThemeCSS(variables: ThemeVariables): string {
    const lines = Object.entries(variables)
        .map(([key, value]) => `   --${key}: ${value};`)
        .join("\n");

    return `
${INJECT_MARKER}
:root[data-theme="custom"] {
${lines}
}
${INJECT_MARKER}
`;
}

function removeExistingCustomTheme(css: string): string {
    const markerRegex = new RegExp(
        `\\n?${INJECT_MARKER.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${INJECT_MARKER.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\n?`,
        "g"
    );
    return css.replace(markerRegex, "");
}

// Marker for identifying the AI-injected theme script in index.html
const HTML_THEME_MARKER_START = '<!-- AI-THEME-START -->';
const HTML_THEME_MARKER_END = '<!-- AI-THEME-END -->';
const INDEX_FILE = path.join(process.cwd(), "index.html");

function injectThemeIntoHTML(themeName: string): void {
    let htmlContent = fs.readFileSync(INDEX_FILE, "utf-8");

    // Remove any existing injected theme
    const markerRegex = new RegExp(
        `${HTML_THEME_MARKER_START}[\\s\\S]*?${HTML_THEME_MARKER_END}\\n?`,
        "g"
    );
    htmlContent = htmlContent.replace(markerRegex, "");

    // Create inline script that runs IMMEDIATELY
    const inlineScript = `${HTML_THEME_MARKER_START}
  <script>
    // Auto-generated by apply-design - Sets theme BEFORE anything else loads
    (function() {
      document.documentElement.setAttribute('data-theme', '${themeName}');
      localStorage.setItem('design-system-theme', '${themeName}');
    })();
  </script>
  ${HTML_THEME_MARKER_END}
`;

    // Insert at the VERY TOP of <head>, right after <head>
    htmlContent = htmlContent.replace('<head>', '<head>\n  ' + inlineScript);
    fs.writeFileSync(INDEX_FILE, htmlContent);
    console.log(`✅ Theme '${themeName}' inlined into ${INDEX_FILE}`);
}

function applyDesign(input: ApplyDesignInput): void {
    let cssContent = fs.readFileSync(CSS_FILE, "utf-8");

    // Remove any existing custom theme
    cssContent = removeExistingCustomTheme(cssContent);

    if (input.customVariables && Object.keys(input.customVariables).length > 0) {
        // Inject custom theme CSS
        const customCSS = generateCustomThemeCSS(input.customVariables);
        cssContent = cssContent + customCSS;
        fs.writeFileSync(CSS_FILE, cssContent);
        console.log(`✅ Custom theme CSS injected into ${CSS_FILE}`);

        // FIXED: Inline theme directly into HTML for synchronous execution
        injectThemeIntoHTML('custom');
    } else if (input.selectedTheme !== undefined) {
        // Use selected theme (no custom CSS needed)
        injectThemeIntoHTML(input.selectedTheme);
    }
}

function main() {
    console.log("🎨 Applying design changes...\n");

    try {
        const input = readInputFile();

        if (!input.selectedTheme && !input.customVariables) {
            console.error("❌ Error: Input must contain 'selectedTheme' or 'customVariables'");
            console.log("\nExample input (design-updated.json):");
            console.log(JSON.stringify({
                selectedTheme: "zen",
                customVariables: {
                    "primary": "#ff6b6b",
                    "secondary": "#4ecdc4",
                }
            }, null, 2));
            process.exit(1);
        }

        applyDesign(input);

        console.log("\n✅ Design applied successfully!");
        console.log("   Restart the dev server to see changes.");
    } catch (error: any) {
        console.error(`❌ Error: ${error.message}`);
        process.exit(1);
    }
}

main();
