import * as fs from "fs";
import * as path from "path";

/**
 * Apply Design System Theme
 * 
 * Takes AI-modified design JSON and applies it to the page.
 * Can either:
 * 1. Set data-theme attribute to use an existing theme
 * 2. Inject custom CSS variables as a new "custom" theme
 */

interface ThemeVariables {
    [key: string]: string;
}

interface ApplyDesignInput {
    selectedTheme?: string;  // Use existing theme by ID
    customVariables?: ThemeVariables;  // Or provide custom variables
}

const CSS_FILE = path.join(process.cwd(), "src", "design-system.css");
const INPUT_FILE = path.join(process.cwd(), "design-updated.json");
const INJECT_MARKER = "/* === AI CUSTOM THEME === */";

function readInputFile(): ApplyDesignInput {
    if (!fs.existsSync(INPUT_FILE)) {
        throw new Error(`Input file not found: ${INPUT_FILE}`);
    }
    return JSON.parse(fs.readFileSync(INPUT_FILE, "utf-8"));
}

function generateCustomThemeCSS(variables: ThemeVariables): string {
    const lines = Object.entries(variables)
        .map(([key, value]) => `   --${key}: ${value};`)
        .join("\n");

    return `
${INJECT_MARKER}
:root[data-theme="custom"] {
${lines}
}
${INJECT_MARKER}
`;
}

function removeExistingCustomTheme(css: string): string {
    const markerRegex = new RegExp(
        `\\n?${INJECT_MARKER.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}[\\s\\S]*?${INJECT_MARKER.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")}\\n?`,
        "g"
    );
    return css.replace(markerRegex, "");
}

function applyDesign(input: ApplyDesignInput): void {
    let cssContent = fs.readFileSync(CSS_FILE, "utf-8");

    // Remove any existing custom theme
    cssContent = removeExistingCustomTheme(cssContent);

    if (input.customVariables && Object.keys(input.customVariables).length > 0) {
        // Inject custom theme CSS
        const customCSS = generateCustomThemeCSS(input.customVariables);
        cssContent = cssContent + customCSS;
        fs.writeFileSync(CSS_FILE, cssContent);
        console.log(`✅ Custom theme injected into ${CSS_FILE}`);

        // FIXED: Force theme to "custom" when custom variables are provided
        const themeInitPath = path.join(process.cwd(), "public", "theme-init.js");
        const themeInitContent = `
// Auto-generated by apply-design script
// Sets the selected theme on page load
(function() {
  document.documentElement.setAttribute('data-theme', 'custom');
  localStorage.setItem('design-system-theme', 'custom');
})();
`;
        fs.writeFileSync(themeInitPath, themeInitContent);
        console.log(`✅ Custom theme will be applied on page load.`);
        console.log(`   Script created: ${themeInitPath}`);
    } else if (input.selectedTheme !== undefined) {
        // Only use selectedTheme if no custom variables provided
        const themeInitPath = path.join(process.cwd(), "public", "theme-init.js");
        const themeInitContent = `
// Auto-generated by apply-design script
// Sets the selected theme on page load
(function() {
  document.documentElement.setAttribute('data-theme', '${input.selectedTheme}');
  localStorage.setItem('design-system-theme', '${input.selectedTheme}');
})();
`;
        fs.writeFileSync(themeInitPath, themeInitContent);
        console.log(`✅ Theme '${input.selectedTheme || "default"}' will be applied on page load.`);
        console.log(`   Script created: ${themeInitPath}`);
    }
}

function main() {
    console.log("🎨 Applying design changes...\n");

    try {
        const input = readInputFile();

        if (!input.selectedTheme && !input.customVariables) {
            console.error("❌ Error: Input must contain 'selectedTheme' or 'customVariables'");
            console.log("\nExample input (design-updated.json):");
            console.log(JSON.stringify({
                selectedTheme: "zen",
                customVariables: {
                    "primary": "#ff6b6b",
                    "secondary": "#4ecdc4",
                }
            }, null, 2));
            process.exit(1);
        }

        applyDesign(input);

        console.log("\n✅ Design applied successfully!");
        console.log("   Restart the dev server to see changes.");
    } catch (error: any) {
        console.error(`❌ Error: ${error.message}`);
        process.exit(1);
    }
}

main();
